# Generated by Django 2.2.2 on 2019-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donanım_dbs',
            name='DURUM',
            field=models.CharField(max_length=100),
        ),
    ]
