# Generated by Django 2.2.2 on 2019-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_auto_20190804_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='sifre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KULLANICI', models.CharField(max_length=100)),
                ('SİFRE', models.CharField(max_length=100)),
            ],
        ),
    ]
